version: "3"

services:
  nr-wireguard:
    image: ghcr.io/tomasliumparas/nr-wireguard:latest
    container_name: nr-wireguard
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    network_mode: host
    environment:
      TS_ENV: "production"
      TS_LOG_LEVEL: "info"
      WIREGUARD_API_URL: "http://sme-vnpnode0:8080/api/v1.0"

