version: "3"

services:
  app:
    image: nr-wireguard
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      TS_ENV: "production"
      TS_LOG_LEVEL: "info"
    ports:
      - 1882:1880
    volumes: []
      # - ./timelog-sync/projects-map.yml:/opt/app-root/src/projects-map.yml
